/**
 * Gemini API Proxy
 * Handles communication with the Google Gemini API.
 * Uses Hungarian notation.
 */

const fnEnhanceTextWithGemini = async (strText, strContext, strApiKey) => {
    if (!strApiKey) {
        throw new Error('API key is required.');
    }
    
    // Construct the prompt based on context
    let strPrompt = '';
    if (strContext === 'job') {
        strPrompt = `You are an expert resume writer. Please take the following raw notes about job responsibilities and rewrite them into professional, impactful, and concise resume bullet points. Focus on action verbs and results if possible. Return ONLY the new bullet points, one per line, with no introductory text or markdown formatting like asterisks or dashes at the start of the line.\n\nRaw notes:\n${strText}`;
    } else if (strContext === 'honors') {
        strPrompt = `You are an expert resume writer. Please take the following raw notes about academic honors and awards and rewrite them into professional, concise resume items. Return ONLY the new items, one per line, with no introductory text or markdown formatting like asterisks or dashes at the start of the line.\n\nRaw notes:\n${strText}`;
    } else if (strContext === 'activities') {
        strPrompt = `You are an expert resume writer. Please take the following raw notes about extracurricular activities and societies and rewrite them into professional, concise resume items. Return ONLY the new items, one per line, with no introductory text or markdown formatting like asterisks or dashes at the start of the line.\n\nRaw notes:\n${strText}`;
    } else {
        strPrompt = `Please rewrite the following text professionally:\n\n${strText}`;
    }

    const strUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${strApiKey}`;
    
    const objPayload = {
        contents: [{
            parts: [{ text: strPrompt }]
        }],
        generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 1024,
        }
    };

    const objResponse = await fetch(strUrl, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(objPayload)
    });

    if (!objResponse.ok) {
        const objError = await objResponse.json();
        throw new Error(objError.error?.message || 'Failed to communicate with Gemini API');
    }

    const objData = await objResponse.json();
    
    if (objData.candidates && objData.candidates.length > 0) {
        const strGeneratedText = objData.candidates[0].content.parts[0].text;
        // Clean up any markdown bullet points Gemini might have included despite instructions
        return strGeneratedText.replace(/^[\*\-\•]\s*/gm, '').trim();
    }
    
    throw new Error('No content generated by Gemini.');
};

module.exports = {
    fnEnhanceTextWithGemini
};
