/**
 * Gemini API Proxy
 * Handles communication with the Google Gemini API.
 * Uses Hungarian notation.
 * 
 * AI Generated: This entire module, including the prompt engineering logic 
 * and fetch implementation, was scaffolded by the Antigravity AI coding assistant.
 */

const { GoogleGenAI } = require('@google/genai');

const fnEnhanceTextWithGemini = async (strText, strContext, strApiKey) => {
    if (!strApiKey) {
        throw new Error('API key is required.');
    }
    
    // Construct the prompt based on context
    let strPrompt = '';
    if (strContext === 'job') {
        strPrompt = `You are an expert resume writer. Please take the following raw notes about job responsibilities and rewrite them into professional, impactful, and concise resume bullet points. Focus on action verbs and results if possible. Return ONLY the new bullet points, one per line, with no introductory text or markdown formatting like asterisks or dashes at the start of the line.\n\nRaw notes:\n${strText}`;
    } else if (strContext === 'honors') {
        strPrompt = `You are an expert resume writer. Please take the following raw notes about academic honors and awards and rewrite them into professional, concise resume items. Return ONLY the new items, one per line, with no introductory text or markdown formatting like asterisks or dashes at the start of the line.\n\nRaw notes:\n${strText}`;
    } else if (strContext === 'activities') {
        strPrompt = `You are an expert resume writer. Please take the following raw notes about extracurricular activities and societies and rewrite them into professional, concise resume items. Return ONLY the new items, one per line, with no introductory text or markdown formatting like asterisks or dashes at the start of the line.\n\nRaw notes:\n${strText}`;
    } else {
        strPrompt = `Please rewrite the following text professionally:\n\n${strText}`;
    }

    const genAI = new GoogleGenAI({ apiKey: strApiKey });
    
    try {
        const objResponse = await genAI.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: strPrompt,
            config: {
                temperature: 0.7,
                topK: 40,
                topP: 0.95,
                maxOutputTokens: 1024,
            }
        });

        const strGeneratedText = objResponse.text;
        if (!strGeneratedText) {
            throw new Error('No content generated by Gemini.');
        }

        // Clean up any markdown bullet points Gemini might have included despite instructions
        return strGeneratedText.replace(/^[\*\-\•]\s*/gm, '').trim();
    } catch (objErr) {
        throw new Error(objErr.message || 'Failed to communicate with Gemini API');
    }
};

module.exports = {
    fnEnhanceTextWithGemini
};
